[2023-11-07 13:24:13,602] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T13:24:12.906686+00:00 [queued]>
[2023-11-07 13:24:13,618] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T13:24:12.906686+00:00 [queued]>
[2023-11-07 13:24:13,618] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 13:24:13,618] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 13:24:13,618] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 13:24:13,639] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 13:24:12.906686+00:00
[2023-11-07 13:24:13,653] {standard_task_runner.py:52} INFO - Started process 174 to run task
[2023-11-07 13:24:13,659] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_test_dag', 'test_selenium', 'manual__2023-11-07T13:24:12.906686+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmptr2wdcu8', '--error-file', '/tmp/tmp0m1g8tcg']
[2023-11-07 13:24:13,661] {standard_task_runner.py:80} INFO - Job 2: Subtask test_selenium
[2023-11-07 13:24:13,787] {task_command.py:370} INFO - Running <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T13:24:12.906686+00:00 [running]> on host 928c1f114a88
[2023-11-07 13:24:13,913] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_test_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T13:24:12.906686+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T13:24:12.906686+00:00
[2023-11-07 13:24:13,915] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 13:24:14,387] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2023-11-07 13:24:14,453] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2023-11-07 13:24:14,484] {logger.py:11} INFO - There is no [linux64] chromedriver "119.0.6045.105" for browser google-chrome "119.0.6045" in cache
[2023-11-07 13:24:14,485] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2023-11-07 13:24:14,557] {logger.py:11} INFO - WebDriver version 119.0.6045.105 selected
[2023-11-07 13:24:14,557] {logger.py:11} INFO - Modern chrome version https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip
[2023-11-07 13:24:14,558] {logger.py:11} INFO - About to download new driver from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip
[2023-11-07 13:24:14,596] {logger.py:11} INFO - Driver downloading response is 200
[2023-11-07 13:24:14,678] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2023-11-07 13:24:14,897] {logger.py:11} INFO - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105]
[2023-11-07 13:24:15,534] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 9, in test_selenium_driver
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x563815a155e3 <unknown>
#1 0x5638156d80b7 <unknown>
#2 0x56381570ee55 <unknown>
#3 0x56381570bb81 <unknown>
#4 0x56381575647f <unknown>
#5 0x56381574ccc3 <unknown>
#6 0x5638157180e4 <unknown>
#7 0x5638157190ae <unknown>
#8 0x5638159dbce1 <unknown>
#9 0x5638159dfb7e <unknown>
#10 0x5638159c94b5 <unknown>
#11 0x5638159e07d6 <unknown>
#12 0x5638159acdbf <unknown>
#13 0x563815a03748 <unknown>
#14 0x563815a03917 <unknown>
#15 0x563815a14773 <unknown>
#16 0x7f85baf1ffa3 start_thread

[2023-11-07 13:24:15,555] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_test_dag, task_id=test_selenium, execution_date=20231107T132412, start_date=20231107T132413, end_date=20231107T132415
[2023-11-07 13:24:15,572] {standard_task_runner.py:92} ERROR - Failed to execute job 2 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x563815a155e3 <unknown>
#1 0x5638156d80b7 <unknown>
#2 0x56381570ee55 <unknown>
#3 0x56381570bb81 <unknown>
#4 0x56381575647f <unknown>
#5 0x56381574ccc3 <unknown>
#6 0x5638157180e4 <unknown>
#7 0x5638157190ae <unknown>
#8 0x5638159dbce1 <unknown>
#9 0x5638159dfb7e <unknown>
#10 0x5638159c94b5 <unknown>
#11 0x5638159e07d6 <unknown>
#12 0x5638159acdbf <unknown>
#13 0x563815a03748 <unknown>
#14 0x563815a03917 <unknown>
#15 0x563815a14773 <unknown>
#16 0x7f85baf1ffa3 start_thread
; 174)
[2023-11-07 13:24:15,601] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 13:24:15,650] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
