[2023-11-07 21:34:39,747] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:29:04.029605+00:00 [queued]>
[2023-11-07 21:34:39,757] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:29:04.029605+00:00 [queued]>
[2023-11-07 21:34:39,757] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:34:39,758] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-11-07 21:34:39,758] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:34:39,773] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:29:04.029605+00:00
[2023-11-07 21:34:39,778] {standard_task_runner.py:52} INFO - Started process 1559 to run task
[2023-11-07 21:34:39,783] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T21:29:04.029605+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpv74_3d_s', '--error-file', '/tmp/tmp641ujfs9']
[2023-11-07 21:34:39,787] {standard_task_runner.py:80} INFO - Job 33: Subtask test_selenium
[2023-11-07 21:34:39,887] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:29:04.029605+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:34:39,991] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:29:04.029605+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:29:04.029605+00:00
[2023-11-07 21:34:39,993] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:34:40,275] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:34:40,333] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:34:40,370] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:34:49,072] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 32, in test_selenium_driver
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 230, in send_keys
    self._execute(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x56036136a5e3 <unknown>
#1 0x56036102cf0d <unknown>
#2 0x56036107496f <unknown>
#3 0x560361072d62 <unknown>
#4 0x5603610a1ef2 <unknown>
#5 0x56036106ea02 <unknown>
#6 0x5603610a20be <unknown>
#7 0x5603610bdb3d <unknown>
#8 0x5603610a1cc3 <unknown>
#9 0x56036106d0e4 <unknown>
#10 0x56036106e0ae <unknown>
#11 0x560361330ce1 <unknown>
#12 0x560361334b7e <unknown>
#13 0x56036131e4b5 <unknown>
#14 0x5603613357d6 <unknown>
#15 0x560361301dbf <unknown>
#16 0x560361358748 <unknown>
#17 0x560361358917 <unknown>
#18 0x560361369773 <unknown>
#19 0x7fef26374ea7 start_thread

[2023-11-07 21:34:49,095] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T212904, start_date=20231107T213439, end_date=20231107T213449
[2023-11-07 21:34:49,113] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task test_selenium (Message: element not interactable
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x56036136a5e3 <unknown>
#1 0x56036102cf0d <unknown>
#2 0x56036107496f <unknown>
#3 0x560361072d62 <unknown>
#4 0x5603610a1ef2 <unknown>
#5 0x56036106ea02 <unknown>
#6 0x5603610a20be <unknown>
#7 0x5603610bdb3d <unknown>
#8 0x5603610a1cc3 <unknown>
#9 0x56036106d0e4 <unknown>
#10 0x56036106e0ae <unknown>
#11 0x560361330ce1 <unknown>
#12 0x560361334b7e <unknown>
#13 0x56036131e4b5 <unknown>
#14 0x5603613357d6 <unknown>
#15 0x560361301dbf <unknown>
#16 0x560361358748 <unknown>
#17 0x560361358917 <unknown>
#18 0x560361369773 <unknown>
#19 0x7fef26374ea7 start_thread
; 1559)
[2023-11-07 21:34:49,130] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:34:49,182] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
