[2023-11-07 21:13:29,436] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:08:26.228489+00:00 [queued]>
[2023-11-07 21:13:29,446] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:08:26.228489+00:00 [queued]>
[2023-11-07 21:13:29,446] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:13:29,446] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-11-07 21:13:29,447] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:13:29,462] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:08:26.228489+00:00
[2023-11-07 21:13:29,469] {standard_task_runner.py:52} INFO - Started process 519 to run task
[2023-11-07 21:13:29,474] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T21:08:26.228489+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmp3_7_1ic0', '--error-file', '/tmp/tmprejupt37']
[2023-11-07 21:13:29,477] {standard_task_runner.py:80} INFO - Job 24: Subtask test_selenium
[2023-11-07 21:13:29,566] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:08:26.228489+00:00 [running]> on host df41b5643cad
[2023-11-07 21:13:29,668] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:08:26.228489+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:08:26.228489+00:00
[2023-11-07 21:13:29,670] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:13:29,980] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:13:30,043] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:13:30,083] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:13:30,723] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 19, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5601fccb35e3 <unknown>
#1 0x5601fc9760b7 <unknown>
#2 0x5601fc9ace55 <unknown>
#3 0x5601fc9a9b81 <unknown>
#4 0x5601fc9f447f <unknown>
#5 0x5601fc9eacc3 <unknown>
#6 0x5601fc9b60e4 <unknown>
#7 0x5601fc9b70ae <unknown>
#8 0x5601fcc79ce1 <unknown>
#9 0x5601fcc7db7e <unknown>
#10 0x5601fcc674b5 <unknown>
#11 0x5601fcc7e7d6 <unknown>
#12 0x5601fcc4adbf <unknown>
#13 0x5601fcca1748 <unknown>
#14 0x5601fcca1917 <unknown>
#15 0x5601fccb2773 <unknown>
#16 0x7fe3110acea7 start_thread

[2023-11-07 21:13:30,743] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T210826, start_date=20231107T211329, end_date=20231107T211330
[2023-11-07 21:13:30,760] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5601fccb35e3 <unknown>
#1 0x5601fc9760b7 <unknown>
#2 0x5601fc9ace55 <unknown>
#3 0x5601fc9a9b81 <unknown>
#4 0x5601fc9f447f <unknown>
#5 0x5601fc9eacc3 <unknown>
#6 0x5601fc9b60e4 <unknown>
#7 0x5601fc9b70ae <unknown>
#8 0x5601fcc79ce1 <unknown>
#9 0x5601fcc7db7e <unknown>
#10 0x5601fcc674b5 <unknown>
#11 0x5601fcc7e7d6 <unknown>
#12 0x5601fcc4adbf <unknown>
#13 0x5601fcca1748 <unknown>
#14 0x5601fcca1917 <unknown>
#15 0x5601fccb2773 <unknown>
#16 0x7fe3110acea7 start_thread
; 519)
[2023-11-07 21:13:30,809] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:13:30,859] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
