[2023-11-07 21:22:31,870] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:22:30.841155+00:00 [queued]>
[2023-11-07 21:22:31,881] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:22:30.841155+00:00 [queued]>
[2023-11-07 21:22:31,881] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:22:31,881] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:22:31,881] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:22:31,895] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:22:30.841155+00:00
[2023-11-07 21:22:31,901] {standard_task_runner.py:52} INFO - Started process 297 to run task
[2023-11-07 21:22:31,906] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T21:22:30.841155+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpbez4hb5o', '--error-file', '/tmp/tmpdo5wnz0p']
[2023-11-07 21:22:31,908] {standard_task_runner.py:80} INFO - Job 28: Subtask test_selenium
[2023-11-07 21:22:31,990] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:22:30.841155+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:22:32,094] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:22:30.841155+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:22:30.841155+00:00
[2023-11-07 21:22:32,095] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:22:32,389] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:22:32,446] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:22:32,487] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:22:33,129] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 18, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559c81d215e3 <unknown>
#1 0x559c819e40b7 <unknown>
#2 0x559c81a1ae55 <unknown>
#3 0x559c81a17b81 <unknown>
#4 0x559c81a6247f <unknown>
#5 0x559c81a58cc3 <unknown>
#6 0x559c81a240e4 <unknown>
#7 0x559c81a250ae <unknown>
#8 0x559c81ce7ce1 <unknown>
#9 0x559c81cebb7e <unknown>
#10 0x559c81cd54b5 <unknown>
#11 0x559c81cec7d6 <unknown>
#12 0x559c81cb8dbf <unknown>
#13 0x559c81d0f748 <unknown>
#14 0x559c81d0f917 <unknown>
#15 0x559c81d20773 <unknown>
#16 0x7fd1e1529ea7 start_thread

[2023-11-07 21:22:33,155] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T212230, start_date=20231107T212231, end_date=20231107T212233
[2023-11-07 21:22:33,173] {standard_task_runner.py:92} ERROR - Failed to execute job 28 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559c81d215e3 <unknown>
#1 0x559c819e40b7 <unknown>
#2 0x559c81a1ae55 <unknown>
#3 0x559c81a17b81 <unknown>
#4 0x559c81a6247f <unknown>
#5 0x559c81a58cc3 <unknown>
#6 0x559c81a240e4 <unknown>
#7 0x559c81a250ae <unknown>
#8 0x559c81ce7ce1 <unknown>
#9 0x559c81cebb7e <unknown>
#10 0x559c81cd54b5 <unknown>
#11 0x559c81cec7d6 <unknown>
#12 0x559c81cb8dbf <unknown>
#13 0x559c81d0f748 <unknown>
#14 0x559c81d0f917 <unknown>
#15 0x559c81d20773 <unknown>
#16 0x7fd1e1529ea7 start_thread
; 297)
[2023-11-07 21:22:33,205] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:22:33,259] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
