[2023-11-07 21:19:44,994] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:19:44.078903+00:00 [queued]>
[2023-11-07 21:19:45,005] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:19:44.078903+00:00 [queued]>
[2023-11-07 21:19:45,006] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:19:45,006] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:19:45,006] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:19:45,022] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:19:44.078903+00:00
[2023-11-07 21:19:45,028] {standard_task_runner.py:52} INFO - Started process 196 to run task
[2023-11-07 21:19:45,033] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T21:19:44.078903+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmp3rsdoptf', '--error-file', '/tmp/tmpqvqx6as9']
[2023-11-07 21:19:45,036] {standard_task_runner.py:80} INFO - Job 27: Subtask test_selenium
[2023-11-07 21:19:45,145] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:19:44.078903+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:19:45,254] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:19:44.078903+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:19:44.078903+00:00
[2023-11-07 21:19:45,256] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:19:45,581] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:19:45,643] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:19:45,680] {logger.py:11} INFO - There is no [linux64] chromedriver "119.0.6045.105" for browser chromium "119.0.6045" in cache
[2023-11-07 21:19:45,680] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:19:45,754] {logger.py:11} INFO - WebDriver version 119.0.6045.105 selected
[2023-11-07 21:19:45,755] {logger.py:11} INFO - Modern chrome version https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip
[2023-11-07 21:19:45,755] {logger.py:11} INFO - About to download new driver from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip
[2023-11-07 21:19:45,825] {logger.py:11} INFO - Driver downloading response is 200
[2023-11-07 21:19:45,910] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:19:46,130] {logger.py:11} INFO - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105]
[2023-11-07 21:19:46,766] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 19, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559b840065e3 <unknown>
#1 0x559b83cc90b7 <unknown>
#2 0x559b83cffe55 <unknown>
#3 0x559b83cfcb81 <unknown>
#4 0x559b83d4747f <unknown>
#5 0x559b83d3dcc3 <unknown>
#6 0x559b83d090e4 <unknown>
#7 0x559b83d0a0ae <unknown>
#8 0x559b83fccce1 <unknown>
#9 0x559b83fd0b7e <unknown>
#10 0x559b83fba4b5 <unknown>
#11 0x559b83fd17d6 <unknown>
#12 0x559b83f9ddbf <unknown>
#13 0x559b83ff4748 <unknown>
#14 0x559b83ff4917 <unknown>
#15 0x559b84005773 <unknown>
#16 0x7f5dbe0dfea7 start_thread

[2023-11-07 21:19:46,788] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T211944, start_date=20231107T211944, end_date=20231107T211946
[2023-11-07 21:19:46,804] {standard_task_runner.py:92} ERROR - Failed to execute job 27 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559b840065e3 <unknown>
#1 0x559b83cc90b7 <unknown>
#2 0x559b83cffe55 <unknown>
#3 0x559b83cfcb81 <unknown>
#4 0x559b83d4747f <unknown>
#5 0x559b83d3dcc3 <unknown>
#6 0x559b83d090e4 <unknown>
#7 0x559b83d0a0ae <unknown>
#8 0x559b83fccce1 <unknown>
#9 0x559b83fd0b7e <unknown>
#10 0x559b83fba4b5 <unknown>
#11 0x559b83fd17d6 <unknown>
#12 0x559b83f9ddbf <unknown>
#13 0x559b83ff4748 <unknown>
#14 0x559b83ff4917 <unknown>
#15 0x559b84005773 <unknown>
#16 0x7f5dbe0dfea7 start_thread
; 196)
[2023-11-07 21:19:46,854] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:19:46,909] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
