[2023-11-08T07:44:25.476+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:44:25.488+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:44:25.489+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-08T07:44:25.505+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 00:00:00+00:00
[2023-11-08T07:44:25.515+0000] {standard_task_runner.py:57} INFO - Started process 280 to run task
[2023-11-08T07:44:25.522+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpp7xv_sfp']
[2023-11-08T07:44:25.527+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask dbt_run
[2023-11-08T07:44:25.629+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [running]> on host e365784c7cfe
[2023-11-08T07:44:25.941+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-08T07:44:25.944+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T07:44:25.945+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models first_model --project-dir /app/airflow/dbt_nba && echo ok']
[2023-11-08T07:44:25.969+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T07:44:33.439+0000] {subprocess.py:93} INFO - [0m07:44:33  Running with dbt=1.7.0
[2023-11-08T07:44:33.446+0000] {subprocess.py:93} INFO - [0m07:44:33  Encountered an error:
[2023-11-08T07:44:33.446+0000] {subprocess.py:93} INFO - Runtime Error
[2023-11-08T07:44:33.446+0000] {subprocess.py:93} INFO -   Could not find profile named 'nba_stats'
[2023-11-08T07:44:34.157+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-08T07:44:34.181+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-08T07:44:34.186+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T000000, start_date=20231108T074425, end_date=20231108T074434
[2023-11-08T07:44:34.210+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 280)
[2023-11-08T07:44:34.233+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T07:44:34.260+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-08T07:54:11.571+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:54:11.585+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:54:11.585+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-08T07:54:11.601+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 00:00:00+00:00
[2023-11-08T07:54:11.610+0000] {standard_task_runner.py:57} INFO - Started process 169 to run task
[2023-11-08T07:54:11.618+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpwnd4c19k']
[2023-11-08T07:54:11.622+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask dbt_run
[2023-11-08T07:54:11.720+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [running]> on host e37a8383d3d6
[2023-11-08T07:54:11.902+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-08T07:54:11.907+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T07:54:11.910+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /app/airflow/dbt_nba']
[2023-11-08T07:54:11.939+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T07:54:18.133+0000] {subprocess.py:93} INFO - [0m07:54:18  Running with dbt=1.7.0
[2023-11-08T07:54:18.140+0000] {subprocess.py:93} INFO - [0m07:54:18  Encountered an error:
[2023-11-08T07:54:18.140+0000] {subprocess.py:93} INFO - Runtime Error
[2023-11-08T07:54:18.141+0000] {subprocess.py:93} INFO -   Could not find profile named 'nba_stats'
[2023-11-08T07:54:18.870+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-08T07:54:18.902+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-08T07:54:18.910+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T000000, start_date=20231108T075411, end_date=20231108T075418
[2023-11-08T07:54:18.945+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 169)
[2023-11-08T07:54:18.975+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T07:54:19.012+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
