[2023-11-07 17:39:49,978] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T17:39:49.144965+00:00 [queued]>
[2023-11-07 17:39:49,989] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T17:39:49.144965+00:00 [queued]>
[2023-11-07 17:39:49,990] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:39:49,990] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 17:39:49,991] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:39:50,007] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 17:39:49.144965+00:00
[2023-11-07 17:39:50,014] {standard_task_runner.py:52} INFO - Started process 240 to run task
[2023-11-07 17:39:50,019] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T17:39:49.144965+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpt2i05mmd', '--error-file', '/tmp/tmp2jyh6osb']
[2023-11-07 17:39:50,022] {standard_task_runner.py:80} INFO - Job 13: Subtask test_selenium
[2023-11-07 17:39:50,123] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T17:39:49.144965+00:00 [running]> on host 910bfbe27458
[2023-11-07 17:39:50,238] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T17:39:49.144965+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T17:39:49.144965+00:00
[2023-11-07 17:39:50,239] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 17:39:50,541] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:39:50,600] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:39:50,646] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 17:39:51,289] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 15, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55cb07a965e3 <unknown>
#1 0x55cb077590b7 <unknown>
#2 0x55cb0778fe55 <unknown>
#3 0x55cb0778cb81 <unknown>
#4 0x55cb077d747f <unknown>
#5 0x55cb077cdcc3 <unknown>
#6 0x55cb077990e4 <unknown>
#7 0x55cb0779a0ae <unknown>
#8 0x55cb07a5cce1 <unknown>
#9 0x55cb07a60b7e <unknown>
#10 0x55cb07a4a4b5 <unknown>
#11 0x55cb07a617d6 <unknown>
#12 0x55cb07a2ddbf <unknown>
#13 0x55cb07a84748 <unknown>
#14 0x55cb07a84917 <unknown>
#15 0x55cb07a95773 <unknown>
#16 0x7ff5d58f8ea7 start_thread

[2023-11-07 17:39:51,315] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T173949, start_date=20231107T173949, end_date=20231107T173951
[2023-11-07 17:39:51,336] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55cb07a965e3 <unknown>
#1 0x55cb077590b7 <unknown>
#2 0x55cb0778fe55 <unknown>
#3 0x55cb0778cb81 <unknown>
#4 0x55cb077d747f <unknown>
#5 0x55cb077cdcc3 <unknown>
#6 0x55cb077990e4 <unknown>
#7 0x55cb0779a0ae <unknown>
#8 0x55cb07a5cce1 <unknown>
#9 0x55cb07a60b7e <unknown>
#10 0x55cb07a4a4b5 <unknown>
#11 0x55cb07a617d6 <unknown>
#12 0x55cb07a2ddbf <unknown>
#13 0x55cb07a84748 <unknown>
#14 0x55cb07a84917 <unknown>
#15 0x55cb07a95773 <unknown>
#16 0x7ff5d58f8ea7 start_thread
; 240)
[2023-11-07 17:39:51,356] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 17:39:51,416] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
