[2023-11-07 17:34:30,888] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T17:34:29.739696+00:00 [queued]>
[2023-11-07 17:34:30,899] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T17:34:29.739696+00:00 [queued]>
[2023-11-07 17:34:30,899] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:34:30,899] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 17:34:30,899] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:34:30,914] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 17:34:29.739696+00:00
[2023-11-07 17:34:30,922] {standard_task_runner.py:52} INFO - Started process 362 to run task
[2023-11-07 17:34:30,926] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T17:34:29.739696+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpwfhk3qke', '--error-file', '/tmp/tmp8t5zsgbk']
[2023-11-07 17:34:30,929] {standard_task_runner.py:80} INFO - Job 10: Subtask test_selenium
[2023-11-07 17:34:31,017] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T17:34:29.739696+00:00 [running]> on host 10d6121935ad
[2023-11-07 17:34:31,112] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T17:34:29.739696+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T17:34:29.739696+00:00
[2023-11-07 17:34:31,114] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 17:34:31,420] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:34:31,479] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:34:31,519] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 17:34:32,156] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 15, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56395ddd55e3 <unknown>
#1 0x56395da980b7 <unknown>
#2 0x56395dacee55 <unknown>
#3 0x56395dacbb81 <unknown>
#4 0x56395db1647f <unknown>
#5 0x56395db0ccc3 <unknown>
#6 0x56395dad80e4 <unknown>
#7 0x56395dad90ae <unknown>
#8 0x56395dd9bce1 <unknown>
#9 0x56395dd9fb7e <unknown>
#10 0x56395dd894b5 <unknown>
#11 0x56395dda07d6 <unknown>
#12 0x56395dd6cdbf <unknown>
#13 0x56395ddc3748 <unknown>
#14 0x56395ddc3917 <unknown>
#15 0x56395ddd4773 <unknown>
#16 0x7f2242d09ea7 start_thread

[2023-11-07 17:34:32,177] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T173429, start_date=20231107T173430, end_date=20231107T173432
[2023-11-07 17:34:32,196] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56395ddd55e3 <unknown>
#1 0x56395da980b7 <unknown>
#2 0x56395dacee55 <unknown>
#3 0x56395dacbb81 <unknown>
#4 0x56395db1647f <unknown>
#5 0x56395db0ccc3 <unknown>
#6 0x56395dad80e4 <unknown>
#7 0x56395dad90ae <unknown>
#8 0x56395dd9bce1 <unknown>
#9 0x56395dd9fb7e <unknown>
#10 0x56395dd894b5 <unknown>
#11 0x56395dda07d6 <unknown>
#12 0x56395dd6cdbf <unknown>
#13 0x56395ddc3748 <unknown>
#14 0x56395ddc3917 <unknown>
#15 0x56395ddd4773 <unknown>
#16 0x7f2242d09ea7 start_thread
; 362)
[2023-11-07 17:34:32,224] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 17:34:32,282] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
