[2023-11-07 17:34:08,325] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:33:02.307507+00:00 [queued]>
[2023-11-07 17:34:08,342] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:33:02.307507+00:00 [queued]>
[2023-11-07 17:34:08,342] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:34:08,342] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2023-11-07 17:34:08,342] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:34:08,365] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 17:33:02.307507+00:00
[2023-11-07 17:34:08,372] {standard_task_runner.py:52} INFO - Started process 286 to run task
[2023-11-07 17:34:08,378] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_test_dag', 'test_selenium', 'manual__2023-11-07T17:33:02.307507+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpzt8lakkt', '--error-file', '/tmp/tmp8hlbxyaq']
[2023-11-07 17:34:08,382] {standard_task_runner.py:80} INFO - Job 9: Subtask test_selenium
[2023-11-07 17:34:08,491] {task_command.py:370} INFO - Running <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:33:02.307507+00:00 [running]> on host 10d6121935ad
[2023-11-07 17:34:08,600] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_test_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T17:33:02.307507+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T17:33:02.307507+00:00
[2023-11-07 17:34:08,601] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 17:34:08,885] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:34:08,945] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:34:08,989] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 17:34:09,630] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 15, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55bdd60705e3 <unknown>
#1 0x55bdd5d330b7 <unknown>
#2 0x55bdd5d69e55 <unknown>
#3 0x55bdd5d66b81 <unknown>
#4 0x55bdd5db147f <unknown>
#5 0x55bdd5da7cc3 <unknown>
#6 0x55bdd5d730e4 <unknown>
#7 0x55bdd5d740ae <unknown>
#8 0x55bdd6036ce1 <unknown>
#9 0x55bdd603ab7e <unknown>
#10 0x55bdd60244b5 <unknown>
#11 0x55bdd603b7d6 <unknown>
#12 0x55bdd6007dbf <unknown>
#13 0x55bdd605e748 <unknown>
#14 0x55bdd605e917 <unknown>
#15 0x55bdd606f773 <unknown>
#16 0x7fb986f44ea7 start_thread

[2023-11-07 17:34:09,657] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_test_dag, task_id=test_selenium, execution_date=20231107T173302, start_date=20231107T173408, end_date=20231107T173409
[2023-11-07 17:34:09,679] {standard_task_runner.py:92} ERROR - Failed to execute job 9 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55bdd60705e3 <unknown>
#1 0x55bdd5d330b7 <unknown>
#2 0x55bdd5d69e55 <unknown>
#3 0x55bdd5d66b81 <unknown>
#4 0x55bdd5db147f <unknown>
#5 0x55bdd5da7cc3 <unknown>
#6 0x55bdd5d730e4 <unknown>
#7 0x55bdd5d740ae <unknown>
#8 0x55bdd6036ce1 <unknown>
#9 0x55bdd603ab7e <unknown>
#10 0x55bdd60244b5 <unknown>
#11 0x55bdd603b7d6 <unknown>
#12 0x55bdd6007dbf <unknown>
#13 0x55bdd605e748 <unknown>
#14 0x55bdd605e917 <unknown>
#15 0x55bdd606f773 <unknown>
#16 0x7fb986f44ea7 start_thread
; 286)
[2023-11-07 17:34:09,717] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 17:34:09,780] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
