[2023-11-07 17:33:03,029] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:33:02.307507+00:00 [queued]>
[2023-11-07 17:33:03,041] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:33:02.307507+00:00 [queued]>
[2023-11-07 17:33:03,041] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:33:03,041] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 17:33:03,041] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:33:03,059] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 17:33:02.307507+00:00
[2023-11-07 17:33:03,066] {standard_task_runner.py:52} INFO - Started process 205 to run task
[2023-11-07 17:33:03,071] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_test_dag', 'test_selenium', 'manual__2023-11-07T17:33:02.307507+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpa0a_rpi9', '--error-file', '/tmp/tmpzcob9vc4']
[2023-11-07 17:33:03,074] {standard_task_runner.py:80} INFO - Job 8: Subtask test_selenium
[2023-11-07 17:33:03,164] {task_command.py:370} INFO - Running <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:33:02.307507+00:00 [running]> on host 10d6121935ad
[2023-11-07 17:33:03,278] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_test_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T17:33:02.307507+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T17:33:02.307507+00:00
[2023-11-07 17:33:03,279] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 17:33:03,569] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:33:03,754] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:33:03,790] {logger.py:11} INFO - There is no [linux64] chromedriver "119.0.6045.105" for browser chromium "119.0.6045" in cache
[2023-11-07 17:33:03,790] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:33:03,867] {logger.py:11} INFO - WebDriver version 119.0.6045.105 selected
[2023-11-07 17:33:03,868] {logger.py:11} INFO - Modern chrome version https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip
[2023-11-07 17:33:03,868] {logger.py:11} INFO - About to download new driver from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip
[2023-11-07 17:33:03,912] {logger.py:11} INFO - Driver downloading response is 200
[2023-11-07 17:33:03,979] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:33:04,174] {logger.py:11} INFO - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105]
[2023-11-07 17:33:04,871] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 15, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56280c1405e3 <unknown>
#1 0x56280be030b7 <unknown>
#2 0x56280be39e55 <unknown>
#3 0x56280be36b81 <unknown>
#4 0x56280be8147f <unknown>
#5 0x56280be77cc3 <unknown>
#6 0x56280be430e4 <unknown>
#7 0x56280be440ae <unknown>
#8 0x56280c106ce1 <unknown>
#9 0x56280c10ab7e <unknown>
#10 0x56280c0f44b5 <unknown>
#11 0x56280c10b7d6 <unknown>
#12 0x56280c0d7dbf <unknown>
#13 0x56280c12e748 <unknown>
#14 0x56280c12e917 <unknown>
#15 0x56280c13f773 <unknown>
#16 0x7f4bd584aea7 start_thread

[2023-11-07 17:33:04,895] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_test_dag, task_id=test_selenium, execution_date=20231107T173302, start_date=20231107T173303, end_date=20231107T173304
[2023-11-07 17:33:04,912] {standard_task_runner.py:92} ERROR - Failed to execute job 8 for task test_selenium (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56280c1405e3 <unknown>
#1 0x56280be030b7 <unknown>
#2 0x56280be39e55 <unknown>
#3 0x56280be36b81 <unknown>
#4 0x56280be8147f <unknown>
#5 0x56280be77cc3 <unknown>
#6 0x56280be430e4 <unknown>
#7 0x56280be440ae <unknown>
#8 0x56280c106ce1 <unknown>
#9 0x56280c10ab7e <unknown>
#10 0x56280c0f44b5 <unknown>
#11 0x56280c10b7d6 <unknown>
#12 0x56280c0d7dbf <unknown>
#13 0x56280c12e748 <unknown>
#14 0x56280c12e917 <unknown>
#15 0x56280c13f773 <unknown>
#16 0x7f4bd584aea7 start_thread
; 205)
[2023-11-07 17:33:04,933] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 17:33:04,986] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
