[2023-11-07 17:26:01,682] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:26:00.574625+00:00 [queued]>
[2023-11-07 17:26:01,703] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:26:00.574625+00:00 [queued]>
[2023-11-07 17:26:01,703] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:26:01,703] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 17:26:01,704] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 17:26:01,728] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 17:26:00.574625+00:00
[2023-11-07 17:26:01,737] {standard_task_runner.py:52} INFO - Started process 174 to run task
[2023-11-07 17:26:01,743] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_test_dag', 'test_selenium', 'manual__2023-11-07T17:26:00.574625+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmprvo7p2mt', '--error-file', '/tmp/tmpigcmrn88']
[2023-11-07 17:26:01,747] {standard_task_runner.py:80} INFO - Job 6: Subtask test_selenium
[2023-11-07 17:26:01,887] {task_command.py:370} INFO - Running <TaskInstance: selenium_test_dag.test_selenium manual__2023-11-07T17:26:00.574625+00:00 [running]> on host cc1d28b994ea
[2023-11-07 17:26:02,052] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_test_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T17:26:00.574625+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T17:26:00.574625+00:00
[2023-11-07 17:26:02,054] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 17:26:02,874] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:26:03,045] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:26:03,176] {logger.py:11} INFO - There is no [linux64] chromedriver "90.0.4430.24" for browser chromium "90.0.4430" in cache
[2023-11-07 17:26:03,178] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:26:03,309] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
[2023-11-07 17:26:03,459] {logger.py:11} INFO - Driver downloading response is 200
[2023-11-07 17:26:04,151] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 17:26:04,400] {logger.py:11} INFO - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/90.0.4430.24]
[2023-11-07 17:26:05,138] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 15, in test_selenium_driver
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55e371beae89 <unknown>

[2023-11-07 17:26:05,161] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_test_dag, task_id=test_selenium, execution_date=20231107T172600, start_date=20231107T172601, end_date=20231107T172605
[2023-11-07 17:26:05,179] {standard_task_runner.py:92} ERROR - Failed to execute job 6 for task test_selenium (Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55e371beae89 <unknown>
; 174)
[2023-11-07 17:26:05,215] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 17:26:05,279] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
